version: '3.7'

services:
  web:
      build:
        context: .
      volumes:
        - static:/static
      #command: gunicorn drf.wsgi:application --bind 0.0.0.0:8000
      ports:
        - 8000:8000
      depends_on:
        - db
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:  
  static: